version: '2'
services: 
  ftp:
    image: stilliard/pure-ftpd:hardened   
    ports:
    - 21:21
    - 30000-30009:30000-30009
    volumes:
      - ./data:/home/ftp
      - ./passwd:/etc/pure-ftpd/passwd
    environment:
      - FTP_USER_NAME=ftp
      - FTP_USER_PASS=12345
      - FTP_USER_HOME=/home/ftp
    command: /run.sh  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -X -x   -p 30000:30009 -c 5 -C 5